2023-12-15 18:19:10.943656: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-15 18:19:10.944763: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-15 18:19:10.964953: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-15 18:19:10.964989: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-15 18:19:10.965532: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-15 18:19:10.968835: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-15 18:19:10.968956: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-15 18:19:11.388944: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-12-15 18:19:12.227773: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-12-15 18:19:12.227918: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-12-15 18:19:12.238164: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Keras Uncertainty will use standalone Keras backendTraceback (most recent call last):
  File "/home/mtesnar/venvs/mystery/lib/python3.10/site-packages/grpc/_server.py", line 555, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/mtesnar/venvs/mystery/lib/python3.10/site-packages/keras_tuner/src/distribute/oracle_chief.py", line 57, in EndTrial
    self.oracle.end_trial(trial)
  File "/home/mtesnar/venvs/mystery/lib/python3.10/site-packages/keras_tuner/src/engine/oracle.py", line 108, in wrapped_func
    ret_val = func(*args, **kwargs)
  File "/home/mtesnar/venvs/mystery/lib/python3.10/site-packages/keras_tuner/src/engine/oracle.py", line 586, in end_trial
    self._check_consecutive_failures()
  File "/home/mtesnar/venvs/mystery/lib/python3.10/site-packages/keras_tuner/src/engine/oracle.py", line 543, in _check_consecutive_failures
    raise RuntimeError(
RuntimeError: Number of consecutive failures exceeded the limit of 3.

Traceback (most recent call last):
  File "/home/mtesnar/venvs/mystery/lib/python3.10/site-packages/grpc/_server.py", line 555, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/mtesnar/venvs/mystery/lib/python3.10/site-packages/keras_tuner/src/distribute/oracle_chief.py", line 57, in EndTrial
    self.oracle.end_trial(trial)
  File "/home/mtesnar/venvs/mystery/lib/python3.10/site-packages/keras_tuner/src/engine/oracle.py", line 108, in wrapped_func
    ret_val = func(*args, **kwargs)
  File "/home/mtesnar/venvs/mystery/lib/python3.10/site-packages/keras_tuner/src/engine/oracle.py", line 586, in end_trial
    self._check_consecutive_failures()
  File "/home/mtesnar/venvs/mystery/lib/python3.10/site-packages/keras_tuner/src/engine/oracle.py", line 543, in _check_consecutive_failures
    raise RuntimeError(
RuntimeError: Number of consecutive failures exceeded the limit of 3.

