python3: can't open file '/home1/s4740556/mystery/tunes_PAT.py': [Errno 2] No such file or directory

The following have been reloaded with a version change:
  1) GCCcore/11.2.0 => GCCcore/12.2.0
  2) XZ/5.2.5-GCCcore-11.2.0 => XZ/5.2.7-GCCcore-12.2.0
  3) libreadline/8.1-GCCcore-11.2.0 => libreadline/8.2-GCCcore-12.2.0
  4) ncurses/6.2-GCCcore-11.2.0 => ncurses/6.3-GCCcore-12.2.0
  5) zlib/1.2.11-GCCcore-11.2.0 => zlib/1.2.12-GCCcore-12.2.0

error: could not lock config file /home1/s4740556/.gitconfig: File exists
fatal: Unable to create '/home1/s4740556/mystery/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   slurm-6542840.out
	modified:   slurm-6542844.out
	modified:   slurm-6542845.out
	modified:   slurm-6542846.out
	modified:   slurm-6542849.out
	modified:   slurm-6542850.out
	modified:   slurm-6542851.out

no changes added to commit (use "git add" and/or "git commit -a")
